// Generated by Tauraro - Manual fixes applied
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

// Manual Memory Management Functions
static inline void* tauraro_alloc(size_t size) {
    void* ptr = malloc(size);
    if (!ptr) {
        fprintf(stderr, "Tauraro: Memory allocation failed\n");
        exit(1);
    }
    return ptr;
}

static inline void tauraro_free(void* ptr) {
    if (ptr) {
        free(ptr);
    }
}

// Conversion functions
double tauraro_float_from_int(int64_t x) {
    return (double)x;
}

// Functions
int64_t calculate_sum(int64_t n) {
    int64_t total = 0;
    for (int64_t i = 0; i < n; i++) {
        total = total + i;
    }
    return total;
}

int64_t calculate_factorial(int64_t n) {
    if (n <= 1) {
        return 1;
    }
    int64_t result = 1;
    for (int64_t i = 2; i <= n; i++) {
        result = result * i;
    }
    return result;
}

double sum_of_squares(int64_t n) {
    double total = 0;
    for (int64_t i = 0; i < n; i++) {
        double x = tauraro_float_from_int(i);
        double square = x * x;
        total = total + square;
    }
    return total;
}

int64_t fibonacci(int64_t n) {
    if (n <= 1) {
        return n;
    }
    int64_t a = 0;
    int64_t b = 1;
    for (int64_t i = 2; i <= n; i++) {
        int64_t temp = a + b;
        a = b;
        b = temp;
    }
    return b;
}

bool is_prime(int64_t n) {
    if (n <= 1) {
        return false;
    }
    if (n == 2) {
        return true;
    }
    if (n % 2 == 0) {
        return false;
    }
    for (int64_t i = 3; i * i <= n; i += 2) {
        if (n % i == 0) {
            return false;
        }
    }
    return true;
}

int main(int argc, char** argv) {
    printf("=== Native Memory Management Test ===\n");
    
    printf("\n1. Basic calculations:\n");
    int64_t sum_result = calculate_sum(100);
    printf("Sum of 0-99 = %lld\n", (long long)sum_result);
    
    int64_t fact_result = calculate_factorial(10);
    printf("Factorial of 10 = %lld\n", (long long)fact_result);
    
    double squares_result = sum_of_squares(50);
    printf("Sum of squares 0-49 = %.0f\n", squares_result);
    
    printf("\n2. Fibonacci numbers:\n");
    int fib_vals[] = {10, 15, 20, 25};
    for (int j = 0; j < 4; j++) {
        int64_t fib = fibonacci(fib_vals[j]);
        printf("fib(%d) = %lld\n", fib_vals[j], (long long)fib);
    }
    
    printf("\n3. Testing prime check:\n");
    int test_vals[] = {2, 3, 4, 17, 20};
    for (int j = 0; j < 5; j++) {
        bool prime = is_prime(test_vals[j]);
        printf("%d is prime: %s\n", test_vals[j], prime ? "True" : "False");
    }
    
    printf("\n4. Performance test - large calculations:\n");
    int64_t large_sum = calculate_sum(10000);
    printf("Sum of 0-9999 = %lld\n", (long long)large_sum);
    
    double large_squares = sum_of_squares(1000);
    printf("Sum of squares 0-999 = %.0f\n", large_squares);
    
    printf("\n=== All Tests Completed ===\n");
    return 0;
}
